### ISSUE TITLE
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values

### ISSUE THREAD

**Issue by miguel-conde** [statsmaths/kerasR#13] opened 2017-04-27 08:12 UTC
I'm trying kerasR package on tensorflow/theano within an anaconda environment.

Here you can see my setup:

```
library(reticulate)
use_condaenv("tensorflow", required = TRUE)

py_config()
```

Which result is:

```
python:         C:\Users\Miguel\Anaconda3\envs\tensorflow\python.exe
libpython:      C:/Users/Miguel/Anaconda3/envs/tensorflow/python35.dll
pythonhome:     C:\Users\Miguel\ANACON~1\envs\TENSOR~1
version:        3.5.3 |Continuum Analytics, Inc.| (default, Feb 22 2017, 21:28:42) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Miguel\ANACON~1\envs\TENSOR~1\lib\site-packages\numpy
numpy_version:  1.12.1

python versions found: 
 C:\Users\Miguel\Anaconda3\envs\tensorflow\python.exe
 C:\Users\Miguel\ANACON~1\python.exe`
```

Everything looks fine:

```
reticulate::py_available()
```
```
[1] TRUE
```

```
reticulate::import("keras.models")
```
```
Module(keras.models)
```

But when i run this code:

```
library(kerasR)  

mod <- Sequential()  

mod$add(Dense(units = 200, input_shape = 13))
```

This error message is thrown:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64

Detailed traceback: 
  File "c:\users\miguel\documents\github\keras\keras\models.py", line 430, in add layer(x)
  File "c:\users\miguel\documents\github\keras\keras\engine\topology.py", line 558, in __call__ self.build(input_shapes[0])
  File "c:\users\miguel\documents\github\keras\keras\layers\core.py", line 827, in build constraint=self.kernel_constraint)
  File "c:\users\miguel\documents\github\keras\keras\legacy\interfaces.py", line 88, in wrapper return func(*args, **kwargs)
  File "c:\users\miguel\documents\github\keras\keras\engine\topology.py", line 391, in add_weight weight = K.variable(initializer(shape), dtype=dtype, name=name)
  File "c:\users\miguel\documents\github\keras\keras\initializers.py", line 208, in __call__ dtype=dtype, seed=self.seed)
  File "c:\users\miguel\documents\github\keras\keras\backend\tensorflow_backend.py", l
```

Any help, please?

My session info is:

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252   
[3] LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] kerasR_0.4.1   reticulate_0.7

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0    Rcpp_0.12.10   knitr_1.15.1 
```

**Comment by statsmaths** [comment] 2017-04-27 13:52
I ran that code and am not getting the same error. The R code should be converting the input shape that you gave to There are a few things I would suggest trying. First all, grab the most recent version of **kerasR** from github (there are a few bugs that have been fixed from the CRAN version):
```{r}
devtools::install_github("statsmaths/kerasR")
```
However, I am not getting your error on my machine for either the CRAN version or the GitHub one. You could also try not using the conda environment as that is the only noticable difference between your code and mine. If that doesn't solve the problem, could you report your version of Keras (from Python the code is)?
```{py}
import keras
keras.__version__
```
Thanks!

**Comment by schnorte** [comment] 2017-04-27 21:39
I can confirm the same error for my setup:
> mod$add(Dense(units = 50L, input_shape = 13))
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64

---
Keras-Version: 2.0.2
---

Python:

python:         E:\WINPYT~1\PYTHON~1.AMD\python.exe
libpython:      E:/WINPYT~1/PYTHON~1.AMD/python35.dll
pythonhome:     E:\WINPYT~1\PYTHON~1.AMD
version:        3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          E:\WINPYT~1\PYTHON~1.AMD\lib\site-packages\numpy
numpy_version:  1.11.3

---

Perhaps there is a problem in the default behaviour of the _touple_ function of the reticulate package? Seems that it produces a float instead of int, if passed a non-explicit integer
> tuple(13)
(13.0,)
> tuple(13L)
(13,)

**Comment by miguel-conde** [comment] 2017-04-28 05:34
My version of Keras is 2.0.3.

I'm gonna try  not using the conda environment and report the result.

Thx.

**Comment by o869k** [comment] 2017-05-07 20:38
Having the exact same issue like @miguel-conde 
Something with version 3.5 of python or Tensoflow1.1 in windows perhaps.

**Comment by statsmaths** [comment] 2017-05-25 10:20
This error still has me baffled. I cannot replicate it and I'm not sure how it could be getting thrown as it is explicitly converting the input to int32. I tried setting up testing with AppVeyor as I don't have a local version of Windows to test on, but that is still not throwing the error. I do not some users have successfully installed with Python 3 and Windows... Any additional details or work arounds people have found would be greatly appreciated.

**Comment by jiaxinglin** [comment] 2017-05-31 05:54
the int32() function in zzz.R maybe caused this error, but I have any idea to solve this, can  you help me ,thx.
in R :::
 library(reticulate)
> np <- import("numpy")
> type <- import("types")
> a <- 12.36
> b <- np$int32(a)
> type$ClassType(a)
<class 'float'>
> type$ClassType(b)
<class 'float'>

but python is return right ,like this.
a = 12.36
b = np.int32(a)
types.ClassType(a)
Out[27]: float

types.ClassType(b)
Out[28]: numpy.int32

**Comment by jiaxinglin** [comment] 2017-05-31 06:27
in the keras_init.R file, I set line  like this :
modules$builtin <-  import_builtins(convert=FALSE)
modules$np <-       import("numpy", convert=FALSE)
it worked,but need to convert data type by script.
> keras_fit(mod, X_train, Y_train,
+           batch_size = 32, epochs = 200,
+           verbose = 1, validation_split = 0.1)
Error in keras_fit(mod, X_train, Y_train, batch_size = 32, epochs = 200,  : 
  The input to 'y' must a vector or matrix object.
> View(X_train)
> Y_train <- as.matrix(Y_train)
> keras_fit(mod, X_train, Y_train,
+           batch_size = 32, epochs = 200,
+           verbose = 1, validation_split = 0.1)

**Comment by statsmaths** [comment] 2017-06-01 14:21
Okay, I'm still not sure why this was causing an issue for some people, but I believe the dev version 0.6.2 now fixes it. Please download the dev version; @jiaxinglin @o869k, @miguel-conde let me know if this fixes the issue or changes the error message.
```
devtools::install_packages("statsmaths/kerasR")
```

**Comment by miguel-conde** [comment] 2017-06-01 15:39
Nw i'm using a theano backend, but i get:

```{r}
mod$add(Dense(units = 50, input_shape = 13))
```
```
Error in py_call_impl(callable, dots$args, dots$keywords) : AssertionError: size must be a tuple of int or a Theano variable 

Detailed traceback: 

File "C:\Users\Miguel\ANACON~1\envs\deepL\lib\site-packages\keras-2.0.3-py3.5.egg\keras\models.py", line 433, in add layer(x) 
File "C:\Users\Miguel\ANACON~1\envs\deepL\lib\site-packages\keras-2.0.3-py3.5.egg\keras\engine\topology.py", line 558, in __call__ self.build(input_shapes[0]) 
File "C:\Users\Miguel\ANACON~1\envs\deepL\lib\site-packages\keras-2.0.3-py3.5.egg\keras\layers\core.py", line 827, in build constraint=self.kernel_constraint) 
File "C:\Users\Miguel\ANACON~1\envs\deepL\lib\site-packages\keras-2.0.3-py3.5.egg\keras\legacy\interfaces.py", line 88, in wrapper return func(*args, **kwargs) 
File "C:\Users\Miguel\ANACON~1\envs\deepL\lib\site-packages\keras-2.0.3-py3.5.egg\keras\engine\topology.py", line 391, in add_weight weight = K.variable(initializer(shape), dtype=dtype, name=name) 
File "C:\Users\Miguel\ANACON~1\envs\deepL\lib\site-packages\keras-2.0.
```

```
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252   
[3] LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] kerasR_0.6.2   reticulate_0.8

loaded via a namespace (and not attached):
 [1] httr_1.2.1      compiler_3.4.0  R6_2.2.0        tools_3.4.0    
 [5] withr_1.0.2     curl_2.5        Rcpp_0.12.10    memoise_1.1.0  
 [9] knitr_1.15.1    git2r_0.18.0    digest_0.6.12   devtools_1.12.0
```

**Comment by Vogelweide1985** [comment] 2017-06-07 08:04
I'm having the same ErrorMessage like @miguel-conde. Maybe I'm not familiar enough with R but i tryed to access the int32() function in the kerasR.Dense function in R and couldn't find it. Is there something i missed, because i can View the Dense and tuple functions, but not  the int32() in the SourceViewer?

```
function (units, activation = "linear", use_bias = TRUE, kernel_initializer = "glorot_uniform", 
    bias_initializer = "zeros", kernel_regularizer = NULL, bias_regularizer = NULL, 
    activity_regularizer = NULL, kernel_constraint = NULL, bias_constraint = NULL, 
    input_shape = NULL) 
{
    if (is.null(input_shape)) {
        res <- modules$keras.layers.core$Dense(units = int32(units), 
            activation = activation, use_bias = use_bias, kernel_initializer = kernel_initializer, 
            bias_initializer = bias_initializer, kernel_regularizer = kernel_regularizer, 
            bias_regularizer = bias_regularizer, activity_regularizer = activity_regularizer, 
            kernel_constraint = kernel_constraint, bias_constraint = bias_constraint)
    }
    else {
        input_shape <- as.list(input_shape)
        input_shape <- modules$builtin$tuple(**int32(input_shape)**)
        res <- modules$keras.layers.core$Dense(units = int32(units), 
            activation = activation, use_bias = use_bias, kernel_initializer = kernel_initializer, 
            bias_initializer = bias_initializer, kernel_regularizer = kernel_regularizer, 
            bias_regularizer = bias_regularizer, activity_regularizer = activity_regularizer, 
            kernel_constraint = kernel_constraint, bias_constraint = bias_constraint, 
            input_shape = input_shape)
    }
    return(res)
}
```

**Comment by schnorte** [comment] 2017-06-10 20:04
dev version 0.6.2 + @jiaxinglin's fix works for me. Disabling conversion for builtins:

`modules$builtin <- import_builtins(convert=FALSE)`

in keras_init.R solved it.

**Comment by keithdlandry** [comment] 2017-07-24 21:27
adding the line: shape = [int(s) for s in shape]
to topology.py before the line: weight = K.variable(initializer(shape), dtype=dtype, name=name) seemed to work for me

**Comment by stefanfritsch** [comment] 2017-08-14 14:14
For me it only works with @jiaxinglin's fix as well. The current github version is still broken.

**Comment by statsmaths** [comment] 2017-09-13 17:43
I believe this is now fixed in the dev version by now loading the numpy library like this
```{r}
temp <- import("numpy", convert = FALSE)
```
Without the converting turned off, the behavior seemed to differ greatly between version of Python, R, and reticulate.

**Closed by statsmaths** 2017-09-13 17:43 UTC
Labels: bug

**Comment by NicoleRadziwill** [comment] 2017-10-15 04:25
I'm getting the same error at the first step after mod <- Sequential() in the first MNIST example at https://cran.r-project.org/web/packages/kerasR/vignettes/introduction.html using the most recent version of kerasR from github.

My settings are:
<code>
> library(reticulate)
Warning message:
package ‘reticulate’ was built under R version 3.4.2 
> use_condaenv("tf-keras",required=TRUE)
> py_config()
python:         C:\Users\User\Anaconda3\envs\tf-keras\python.exe
libpython:      C:/Users/User/Anaconda3/envs/tf-keras/python35.dll
pythonhome:     C:\Users\User\ANACON~1\envs\tf-keras
version:        3.5.4 |Anaconda custom (64-bit)| (default, Sep 19 2017, 08:15:17) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\User\ANACON~1\envs\tf-keras\lib\site-packages\numpy
numpy_version:  1.13.1
keras:          C:\Users\User\ANACON~1\envs\tf-keras\lib\site-packages\keras

python versions found: 
 C:\Users\User\AppData\Local\conda\conda\envs\r-tensorflow\python.exe
 C:\Users\User\ANACON~1\python.exe
 C:\Users\User\Anaconda3\envs\tf-keras\python.exe
 C:\Users\User\AppData\Local\conda\conda\envs\my_root\python.exe
</code>

I can't find a keras_init.R file anywhere on my Win10 machine so didn't try that fix (but would if I could find that file). If anyone has any other ideas they would be much appreciated.
